# Form implementation generated from reading ui file 'calculatormain1.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 377)
        MainWindow.setStyleSheet("background-color: rgb(245, 248, 254);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.iconnamewgt = QtWidgets.QWidget(parent=self.centralwidget)
        self.iconnamewgt.setStyleSheet("QWidget{\n"
"background-color: rgb(148, 148, 148);\n"
"}\n"
"QPushButton{\n"
"height:30px;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"}\n"
"")
        self.iconnamewgt.setObjectName("iconnamewgt")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.iconnamewgt)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.signout = QtWidgets.QPushButton(parent=self.iconnamewgt)
        self.signout.setStyleSheet("color: rgb(255, 255, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/signoutbtn.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.signout.setIcon(icon)
        self.signout.setCheckable(True)
        self.signout.setObjectName("signout")
        self.gridLayout_2.addWidget(self.signout, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.iconnamewgt)
        self.label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/calcbtn.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.iconnamewgt)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI Semilight")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.overbtn1 = QtWidgets.QPushButton(parent=self.iconnamewgt)
        self.overbtn1.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.overbtn1.setCheckable(True)
        self.overbtn1.setAutoDefault(True)
        self.overbtn1.setObjectName("overbtn1")
        self.verticalLayout_2.addWidget(self.overbtn1)
        self.herobtn1 = QtWidgets.QPushButton(parent=self.iconnamewgt)
        self.herobtn1.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.herobtn1.setCheckable(True)
        self.herobtn1.setObjectName("herobtn1")
        self.verticalLayout_2.addWidget(self.herobtn1)
        self.gamesbtn1 = QtWidgets.QPushButton(parent=self.iconnamewgt)
        self.gamesbtn1.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.gamesbtn1.setCheckable(True)
        self.gamesbtn1.setObjectName("gamesbtn1")
        self.verticalLayout_2.addWidget(self.gamesbtn1)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.iconnamewgt, 0, 1, 2, 1)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setStyleSheet("QWidget{\n"
"background-color: rgb(148, 148, 148);\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_9.setMinimumSize(QtCore.QSize(30, 30))
        self.pushButton_9.setMaximumSize(QtCore.QSize(30, 30))
        self.pushButton_9.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.pushButton_9.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/menubtn.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setAutoExclusive(True)
        self.pushButton_9.setAutoDefault(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout.addWidget(self.pushButton_9)
        spacerItem1 = QtWidgets.QSpacerItem(288, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_10.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_10.setMaximumSize(QtCore.QSize(40, 40))
        self.pushButton_10.setStyleSheet("QWidget{\n"
"    border:none;\n"
"background-color: rgb(148, 148, 148);\n"
"}\n"
"")
        self.pushButton_10.setText("")
        self.pushButton_10.setIcon(icon)
        self.pushButton_10.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setAutoDefault(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_3.addWidget(self.pushButton_10)
        self.gridLayout_3.addWidget(self.widget, 0, 2, 1, 1)
        self.iconwgt = QtWidgets.QWidget(parent=self.centralwidget)
        self.iconwgt.setStyleSheet("QWidget{\n"
"background-color: rgb(148, 148, 148);\n"
"}\n"
"QPushButton{\n"
"height:30px;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"}\n"
"")
        self.iconwgt.setObjectName("iconwgt")
        self.gridLayout = QtWidgets.QGridLayout(self.iconwgt)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=self.iconwgt)
        self.label.setMinimumSize(QtCore.QSize(40, 40))
        self.label.setMaximumSize(QtCore.QSize(40, 40))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/calcbtn.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.overallbtn = QtWidgets.QPushButton(parent=self.iconwgt)
        self.overallbtn.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.overallbtn.setCheckable(True)
        self.overallbtn.setObjectName("overallbtn")
        self.verticalLayout.addWidget(self.overallbtn)
        self.herobtn = QtWidgets.QPushButton(parent=self.iconwgt)
        self.herobtn.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.herobtn.setCheckable(True)
        self.herobtn.setObjectName("herobtn")
        self.verticalLayout.addWidget(self.herobtn)
        self.gamesbtn = QtWidgets.QPushButton(parent=self.iconwgt)
        self.gamesbtn.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.gamesbtn.setCheckable(True)
        self.gamesbtn.setObjectName("gamesbtn")
        self.verticalLayout.addWidget(self.gamesbtn)
        spacerItem2 = QtWidgets.QSpacerItem(20, 150, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.iconwgt)
        self.pushButton_7.setText("")
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setCheckable(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.iconwgt, 0, 0, 2, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.overallpg = QtWidgets.QWidget()
        self.overallpg.setObjectName("overallpg")
        self.label_4 = QtWidgets.QLabel(parent=self.overallpg)
        self.label_4.setGeometry(QtCore.QRect(34, 59, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.overallpg)
        self.label_5.setGeometry(QtCore.QRect(30, 110, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.overallpg)
        self.label_6.setGeometry(QtCore.QRect(30, 160, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.textEdit = QtWidgets.QTextEdit(parent=self.overallpg)
        self.textEdit.setGeometry(QtCore.QRect(220, 70, 131, 31))
        self.textEdit.setOverwriteMode(False)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextEditorInteraction)
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.overallpg)
        self.textEdit_2.setGeometry(QtCore.QRect(220, 120, 131, 31))
        self.textEdit_2.setOverwriteMode(False)
        self.textEdit_2.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextEditorInteraction)
        self.textEdit_2.setObjectName("textEdit_2")
        self.lcdNumber = QtWidgets.QLCDNumber(parent=self.overallpg)
        self.lcdNumber.setGeometry(QtCore.QRect(220, 160, 131, 31))
        self.lcdNumber.setObjectName("lcdNumber")
        self.stackedWidget.addWidget(self.overallpg)
        self.heropg = QtWidgets.QWidget()
        self.heropg.setObjectName("heropg")
        self.label_7 = QtWidgets.QLabel(parent=self.heropg)
        self.label_7.setGeometry(QtCore.QRect(60, 90, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.textEdit_3 = QtWidgets.QTextEdit(parent=self.heropg)
        self.textEdit_3.setGeometry(QtCore.QRect(240, 50, 131, 31))
        self.textEdit_3.setOverwriteMode(False)
        self.textEdit_3.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextEditorInteraction)
        self.textEdit_3.setObjectName("textEdit_3")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(parent=self.heropg)
        self.lcdNumber_2.setGeometry(QtCore.QRect(240, 140, 131, 31))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.label_8 = QtWidgets.QLabel(parent=self.heropg)
        self.label_8.setGeometry(QtCore.QRect(40, 50, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.textEdit_4 = QtWidgets.QTextEdit(parent=self.heropg)
        self.textEdit_4.setGeometry(QtCore.QRect(240, 100, 131, 31))
        self.textEdit_4.setOverwriteMode(False)
        self.textEdit_4.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextEditorInteraction)
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_9 = QtWidgets.QLabel(parent=self.heropg)
        self.label_9.setGeometry(QtCore.QRect(140, 130, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.heropg)
        self.gamespg = QtWidgets.QWidget()
        self.gamespg.setObjectName("gamespg")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(parent=self.gamespg)
        self.lcdNumber_3.setGeometry(QtCore.QRect(260, 150, 131, 31))
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.textEdit_5 = QtWidgets.QTextEdit(parent=self.gamespg)
        self.textEdit_5.setGeometry(QtCore.QRect(260, 60, 131, 31))
        self.textEdit_5.setOverwriteMode(False)
        self.textEdit_5.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextEditorInteraction)
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_10 = QtWidgets.QLabel(parent=self.gamespg)
        self.label_10.setGeometry(QtCore.QRect(50, 150, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.gamespg)
        self.label_11.setGeometry(QtCore.QRect(110, 100, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.textEdit_6 = QtWidgets.QTextEdit(parent=self.gamespg)
        self.textEdit_6.setGeometry(QtCore.QRect(260, 110, 131, 31))
        self.textEdit_6.setOverwriteMode(False)
        self.textEdit_6.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextEditorInteraction)
        self.textEdit_6.setObjectName("textEdit_6")
        self.label_12 = QtWidgets.QLabel(parent=self.gamespg)
        self.label_12.setGeometry(QtCore.QRect(160, 50, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(20)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.stackedWidget.addWidget(self.gamespg)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout_3.addWidget(self.stackedWidget, 1, 2, 1, 1)
        self.iconnamewgt.raise_()
        self.iconwgt.raise_()
        self.widget.raise_()
        self.stackedWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_9.toggled['bool'].connect(self.iconwgt.setHidden) # type: ignore
        self.pushButton_9.toggled['bool'].connect(self.iconnamewgt.setVisible) # type: ignore
        self.gamesbtn.toggled['bool'].connect(self.gamesbtn1.setChecked) # type: ignore
        self.herobtn.toggled['bool'].connect(self.herobtn1.setChecked) # type: ignore
        self.overallbtn.toggled['bool'].connect(self.overbtn1.setChecked) # type: ignore
        self.gamesbtn1.toggled['bool'].connect(self.gamesbtn.setChecked) # type: ignore
        self.herobtn1.toggled['bool'].connect(self.herobtn.setChecked) # type: ignore
        self.pushButton_7.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.signout.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.pushButton_10.toggled['bool'].connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.signout.setText(_translate("MainWindow", "Sign Out"))
        self.label_3.setText(_translate("MainWindow", "WinRate\n"
"Calculator\n"
""))
        self.overbtn1.setText(_translate("MainWindow", "Overall"))
        self.herobtn1.setText(_translate("MainWindow", "Hero"))
        self.gamesbtn1.setText(_translate("MainWindow", "Games Needed"))
        self.overallbtn.setText(_translate("MainWindow", "Overall"))
        self.herobtn.setText(_translate("MainWindow", "Hero"))
        self.gamesbtn.setText(_translate("MainWindow", "Games"))
        self.label_4.setText(_translate("MainWindow", "Number Of Games:"))
        self.label_5.setText(_translate("MainWindow", "Number Of Wins:"))
        self.label_6.setText(_translate("MainWindow", "Winrate:"))
        self.label_7.setText(_translate("MainWindow", "Number Of Wins:"))
        self.label_8.setText(_translate("MainWindow", "Number Of Games:"))
        self.label_9.setText(_translate("MainWindow", "Winrate:"))
        self.label_10.setText(_translate("MainWindow", "Games Won Required:"))
        self.label_11.setText(_translate("MainWindow", "Games Played:"))
        self.label_12.setText(_translate("MainWindow", "WinRate:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
