# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'newpage.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
    QPushButton, QScrollArea, QSizePolicy, QSpacerItem,
    QStackedWidget, QVBoxLayout, QWidget)
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1160, 711)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(0, 0, 161, 711))
        self.widget.setStyleSheet(u"QWidget{\n"
"background-color: rgb(117, 58, 175);\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(71, 142, 213);\n"
"	color: rgb(255, 255, 255);\n"
"}")
        self.layoutWidget = QWidget(self.widget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(9, 9, 150, 681))
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.layoutWidget)
        self.label.setObjectName(u"label")
        self.label.setPixmap(QPixmap(u":/mlbb.jpg"))
        self.label.setScaledContents(True)

        self.verticalLayout.addWidget(self.label)

        self.allhero = QPushButton(self.layoutWidget)
        self.allhero.setObjectName(u"allhero")

        self.verticalLayout.addWidget(self.allhero)

        self.assa = QPushButton(self.layoutWidget)
        self.assa.setObjectName(u"assa")
        icon = QIcon()
        icon.addFile(u":/Assassin_Icon.webp", QSize(), QIcon.Normal, QIcon.Off)
        self.assa.setIcon(icon)
        self.assa.setCheckable(True)

        self.verticalLayout.addWidget(self.assa)

        self.tank = QPushButton(self.layoutWidget)
        self.tank.setObjectName(u"tank")
        icon1 = QIcon()
        icon1.addFile(u":/Tank_Icon.webp", QSize(), QIcon.Normal, QIcon.Off)
        self.tank.setIcon(icon1)
        self.tank.setCheckable(True)

        self.verticalLayout.addWidget(self.tank)

        self.fighter = QPushButton(self.layoutWidget)
        self.fighter.setObjectName(u"fighter")
        icon2 = QIcon()
        icon2.addFile(u":/Fighter_Icon.webp", QSize(), QIcon.Normal, QIcon.Off)
        self.fighter.setIcon(icon2)
        self.fighter.setCheckable(True)

        self.verticalLayout.addWidget(self.fighter)

        self.mage = QPushButton(self.layoutWidget)
        self.mage.setObjectName(u"mage")
        icon3 = QIcon()
        icon3.addFile(u":/Mage_Icon.webp", QSize(), QIcon.Normal, QIcon.Off)
        self.mage.setIcon(icon3)
        self.mage.setCheckable(True)

        self.verticalLayout.addWidget(self.mage)

        self.mm = QPushButton(self.layoutWidget)
        self.mm.setObjectName(u"mm")
        icon4 = QIcon()
        icon4.addFile(u":/Marksman_Icon.webp", QSize(), QIcon.Normal, QIcon.Off)
        self.mm.setIcon(icon4)
        self.mm.setCheckable(True)

        self.verticalLayout.addWidget(self.mm)

        self.sup = QPushButton(self.layoutWidget)
        self.sup.setObjectName(u"sup")
        icon5 = QIcon()
        icon5.addFile(u":/Support_Icon.webp", QSize(), QIcon.Normal, QIcon.Off)
        self.sup.setIcon(icon5)
        self.sup.setCheckable(True)

        self.verticalLayout.addWidget(self.sup)

        self.verticalSpacer = QSpacerItem(20, 325, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer)

        self.cls = QPushButton(self.layoutWidget)
        self.cls.setObjectName(u"cls")
        self.cls.setCheckable(True)

        self.verticalLayout.addWidget(self.cls)

        self.widget_2 = QWidget(self.centralwidget)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(160, -20, 1001, 731))
        self.widget_2.setStyleSheet(u"QWidget{\n"
"background-color: rgb(0, 0, 255);\n"
"}")
        self.stackedWidget = QStackedWidget(self.widget_2)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(30, 30, 941, 681))
        self.stackedWidget.setFocusPolicy(Qt.StrongFocus)
        self.stackedWidget.setStyleSheet(u"\n"
"background-color: rgb(255, 58, 24);")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.scrollArea = QScrollArea(self.page)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(10, 20, 931, 661))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 912, 1218))
        self.scrollAreaWidgetContents.setStyleSheet(u"QScrollBar:vertical{\n"
"border: none;\n"
"background-color: rgb(59,59,90);\n"
"width:14px;\n"
"margin: 15 px 0 15px 0;\n"
"border-radius: 0px;\n"
"}")
        self.verticalLayout_2 = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.frame = QFrame(self.scrollAreaWidgetContents)
        self.frame.setObjectName(u"frame")
        self.frame.setMinimumSize(QSize(0, 1200))
        self.frame.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.Saber = QPushButton(self.frame)
        self.Saber.setObjectName(u"Saber")
        self.Saber.setGeometry(QRect(20, 60, 81, 23))
        self.Saber.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Saber.setCheckable(False)
        self.label_9 = QLabel(self.frame)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 0, 81, 51))
        self.label_9.setPixmap(QPixmap(u":/Saber.png"))
        self.label_9.setScaledContents(True)
        self.Karina = QPushButton(self.frame)
        self.Karina.setObjectName(u"Karina")
        self.Karina.setGeometry(QRect(130, 60, 81, 23))
        self.Karina.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Karina.setCheckable(False)
        self.Alucard = QPushButton(self.frame)
        self.Alucard.setObjectName(u"Alucard")
        self.Alucard.setGeometry(QRect(240, 60, 81, 23))
        self.Alucard.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Alucard.setCheckable(False)
        self.Hayabusa = QPushButton(self.frame)
        self.Hayabusa.setObjectName(u"Hayabusa")
        self.Hayabusa.setGeometry(QRect(440, 60, 81, 23))
        self.Hayabusa.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Hayabusa.setCheckable(False)
        self.Fanny = QPushButton(self.frame)
        self.Fanny.setObjectName(u"Fanny")
        self.Fanny.setGeometry(QRect(340, 60, 81, 23))
        self.Fanny.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Fanny.setCheckable(False)
        self.Natalia = QPushButton(self.frame)
        self.Natalia.setObjectName(u"Natalia")
        self.Natalia.setGeometry(QRect(540, 60, 81, 23))
        self.Natalia.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Natalia.setCheckable(False)
        self.label_10 = QLabel(self.frame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(130, 0, 81, 51))
        self.label_10.setPixmap(QPixmap(u":/Karina.jpg"))
        self.label_10.setScaledContents(True)
        self.label_11 = QLabel(self.frame)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(240, 0, 81, 51))
        self.label_11.setPixmap(QPixmap(u":/Alucard.jpg"))
        self.label_11.setScaledContents(True)
        self.label_12 = QLabel(self.frame)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(340, 0, 81, 51))
        self.label_12.setPixmap(QPixmap(u":/fanny.png"))
        self.label_12.setScaledContents(True)

        self.verticalLayout_2.addWidget(self.frame)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.page)
        self.assaspage = QWidget()
        self.assaspage.setObjectName(u"assaspage")
        self.label_3 = QLabel(self.assaspage)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(280, 10, 341, 41))
        font = QFont()
        font.setFamilies([u"Sitka Banner Semibold"])
        font.setPointSize(19)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.label_3.setAlignment(Qt.AlignCenter)
        self.saber = QPushButton(self.assaspage)
        self.saber.setObjectName(u"saber")
        self.saber.setGeometry(QRect(40, 130, 75, 23))
        self.saber.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.saber.setCheckable(True)
        self.label_8 = QLabel(self.assaspage)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(40, 70, 71, 51))
        self.label_8.setPixmap(QPixmap(u":/Saber.png"))
        self.label_8.setScaledContents(True)
        self.stackedWidget.addWidget(self.assaspage)
        self.tankspage = QWidget()
        self.tankspage.setObjectName(u"tankspage")
        self.label_4 = QLabel(self.tankspage)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(200, 70, 341, 41))
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.label_4.setAlignment(Qt.AlignCenter)
        self.stackedWidget.addWidget(self.tankspage)
        self.fighterspage = QWidget()
        self.fighterspage.setObjectName(u"fighterspage")
        self.label_5 = QLabel(self.fighterspage)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(190, 40, 341, 41))
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.label_5.setAlignment(Qt.AlignCenter)
        self.stackedWidget.addWidget(self.fighterspage)
        self.magepage = QWidget()
        self.magepage.setObjectName(u"magepage")
        self.label_6 = QLabel(self.magepage)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(190, 30, 341, 41))
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.label_6.setAlignment(Qt.AlignCenter)
        self.stackedWidget.addWidget(self.magepage)
        self.mmpage = QWidget()
        self.mmpage.setObjectName(u"mmpage")
        self.label_7 = QLabel(self.mmpage)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(200, 30, 341, 41))
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.label_7.setAlignment(Qt.AlignCenter)
        self.stackedWidget.addWidget(self.mmpage)
        self.supportpage = QWidget()
        self.supportpage.setObjectName(u"supportpage")
        self.label_2 = QLabel(self.supportpage)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(190, 30, 341, 41))
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.stackedWidget.addWidget(self.supportpage)
        self.saberpage = QWidget()
        self.saberpage.setObjectName(u"saberpage")
        self.widget_3 = QWidget(self.saberpage)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(10, 20, 921, 651))
        self.widget_3.setStyleSheet(u"background-color: rgb(149, 0, 149);")
        self.heropic = QLabel(self.widget_3)
        self.heropic.setObjectName(u"heropic")
        self.heropic.setGeometry(QRect(30, 10, 341, 191))
        self.heropic.setPixmap(QPixmap(u":/Saber.png"))
        self.heropic.setScaledContents(True)
        self.heropic.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.Passive_name_label = QLabel(self.widget_3)
        self.Passive_name_label.setObjectName(u"Passive_name_label")
        self.Passive_name_label.setGeometry(QRect(90, 210, 111, 21))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        font1.setUnderline(True)
        self.Passive_name_label.setFont(font1)
        self.Passive_name_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.Passive_name_label.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.Passivelabel = QLabel(self.widget_3)
        self.Passivelabel.setObjectName(u"Passivelabel")
        self.Passivelabel.setGeometry(QRect(20, 200, 61, 21))
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        self.Passivelabel.setFont(font2)
        self.Passivelabel.setStyleSheet(u"color: rgb(85, 255, 127);")
        self.Passivelabel.setOpenExternalLinks(False)
        self.Passivelabel.setTextInteractionFlags(Qt.LinksAccessibleByMouse|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.passivepic = QLabel(self.widget_3)
        self.passivepic.setObjectName(u"passivepic")
        self.passivepic.setGeometry(QRect(20, 220, 47, 51))
        self.passivepic.setPixmap(QPixmap(u":/EnemyBane.png"))
        self.passivepic.setScaledContents(True)
        self.passivepic.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.passivedesc = QLabel(self.widget_3)
        self.passivedesc.setObjectName(u"passivedesc")
        self.passivedesc.setGeometry(QRect(80, 240, 811, 31))
        self.passivedesc.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.passivedesc.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.passivedesc.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.skill1text = QLabel(self.widget_3)
        self.skill1text.setObjectName(u"skill1text")
        self.skill1text.setGeometry(QRect(20, 280, 51, 16))
        self.skill1text.setFont(font2)
        self.skill1text.setStyleSheet(u"color: rgb(85, 255, 127);")
        self.skill1pic = QLabel(self.widget_3)
        self.skill1pic.setObjectName(u"skill1pic")
        self.skill1pic.setGeometry(QRect(20, 300, 51, 51))
        self.skill1pic.setPixmap(QPixmap(u":/Orbiting_Swords.png"))
        self.skill1pic.setScaledContents(True)
        self.skill1pic.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.skill1_name = QLabel(self.widget_3)
        self.skill1_name.setObjectName(u"skill1_name")
        self.skill1_name.setGeometry(QRect(90, 290, 131, 16))
        self.skill1_name.setFont(font1)
        self.skill1_name.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.skill1_name.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.skill1desc = QLabel(self.widget_3)
        self.skill1desc.setObjectName(u"skill1desc")
        self.skill1desc.setGeometry(QRect(90, 310, 811, 71))
        self.skill1desc.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.skill1desc.setWordWrap(True)
        self.skill1desc.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.skill2text = QLabel(self.widget_3)
        self.skill2text.setObjectName(u"skill2text")
        self.skill2text.setGeometry(QRect(20, 380, 61, 21))
        self.skill2text.setFont(font2)
        self.skill2text.setStyleSheet(u"color: rgb(85, 255, 127);")
        self.skill2text.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.skill2pic = QLabel(self.widget_3)
        self.skill2pic.setObjectName(u"skill2pic")
        self.skill2pic.setGeometry(QRect(20, 410, 51, 51))
        self.skill2pic.setPixmap(QPixmap(u":/Charge.png"))
        self.skill2pic.setScaledContents(True)
        self.skill2pic.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.skill2_name = QLabel(self.widget_3)
        self.skill2_name.setObjectName(u"skill2_name")
        self.skill2_name.setGeometry(QRect(90, 390, 131, 21))
        self.skill2_name.setFont(font1)
        self.skill2_name.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.skill2_name.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.skill2desc = QLabel(self.widget_3)
        self.skill2desc.setObjectName(u"skill2desc")
        self.skill2desc.setGeometry(QRect(90, 420, 641, 51))
        self.skill2desc.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.skill2desc.setWordWrap(True)
        self.skill2desc.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.ultimatetext = QLabel(self.widget_3)
        self.ultimatetext.setObjectName(u"ultimatetext")
        self.ultimatetext.setGeometry(QRect(20, 550, 71, 21))
        self.ultimatetext.setFont(font2)
        self.ultimatetext.setStyleSheet(u"color: rgb(85, 255, 127);")
        self.ultimatetext.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.ultipic = QLabel(self.widget_3)
        self.ultipic.setObjectName(u"ultipic")
        self.ultipic.setGeometry(QRect(30, 580, 51, 51))
        self.ultipic.setPixmap(QPixmap(u":/Triple_Sweep.png"))
        self.ultipic.setScaledContents(True)
        self.ultipic.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.Ultimatename = QLabel(self.widget_3)
        self.Ultimatename.setObjectName(u"Ultimatename")
        self.Ultimatename.setGeometry(QRect(100, 555, 151, 21))
        self.Ultimatename.setFont(font1)
        self.Ultimatename.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.Ultimatename.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.ultimatedesc = QLabel(self.widget_3)
        self.ultimatedesc.setObjectName(u"ultimatedesc")
        self.ultimatedesc.setGeometry(QRect(100, 580, 641, 51))
        self.ultimatedesc.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ultimatedesc.setWordWrap(True)
        self.ultimatedesc.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.specialskilltext = QLabel(self.widget_3)
        self.specialskilltext.setObjectName(u"specialskilltext")
        self.specialskilltext.setGeometry(QRect(0, 480, 111, 16))
        self.specialskilltext.setFont(font2)
        self.specialskilltext.setStyleSheet(u"color: rgb(85, 255, 127);")
        self.specialskilldesc = QLabel(self.widget_3)
        self.specialskilldesc.setObjectName(u"specialskilldesc")
        self.specialskilldesc.setGeometry(QRect(110, 510, 641, 31))
        self.specialskilldesc.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.specialskilldesc.setWordWrap(True)
        self.specialskilldesc.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.specialskillpic = QLabel(self.widget_3)
        self.specialskillpic.setObjectName(u"specialskillpic")
        self.specialskillpic.setGeometry(QRect(30, 510, 47, 14))
        self.specialskillpic.setStyleSheet(u"background-color: rgb(255, 170, 255);")
        self.specialskillpic.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.Specialskillname = QLabel(self.widget_3)
        self.Specialskillname.setObjectName(u"Specialskillname")
        self.Specialskillname.setGeometry(QRect(110, 480, 91, 16))
        self.Specialskillname.setFont(font1)
        self.Specialskillname.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.Specialskillname.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.stackedWidget.addWidget(self.saberpage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.cls.clicked["bool"].connect(MainWindow.close)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText("")
        self.allhero.setText(QCoreApplication.translate("MainWindow", u"All ", None))
        self.assa.setText(QCoreApplication.translate("MainWindow", u"Assassins", None))
        self.tank.setText(QCoreApplication.translate("MainWindow", u"Tank", None))
        self.fighter.setText(QCoreApplication.translate("MainWindow", u"Fighter", None))
        self.mage.setText(QCoreApplication.translate("MainWindow", u"Mage", None))
        self.mm.setText(QCoreApplication.translate("MainWindow", u"Marksman", None))
        self.sup.setText(QCoreApplication.translate("MainWindow", u"Support", None))
        self.cls.setText(QCoreApplication.translate("MainWindow", u"Close", None))
#if QT_CONFIG(accessibility)
        self.Saber.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Saber.setText(QCoreApplication.translate("MainWindow", u"Saber", None))
        self.label_9.setText("")
        self.Karina.setText(QCoreApplication.translate("MainWindow", u"Karina", None))
        self.Alucard.setText(QCoreApplication.translate("MainWindow", u"Alucard", None))
        self.Hayabusa.setText(QCoreApplication.translate("MainWindow", u"Hayabusa", None))
        self.Fanny.setText(QCoreApplication.translate("MainWindow", u"Fanny", None))
        self.Natalia.setText(QCoreApplication.translate("MainWindow", u"Natalia", None))
        self.label_10.setText("")
        self.label_11.setText("")
        self.label_12.setText("")
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Assassins", None))
        self.saber.setText(QCoreApplication.translate("MainWindow", u"Saber", None))
        self.label_8.setText("")
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Tanks", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Fighters", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Mage", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Marksman", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Supports", None))
        self.heropic.setText("")
        self.Passive_name_label.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.Passivelabel.setText(QCoreApplication.translate("MainWindow", u"Passive", None))
        self.passivepic.setText("")
        self.passivedesc.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.skill1text.setText(QCoreApplication.translate("MainWindow", u"Skill 1", None))
        self.skill1pic.setText("")
        self.skill1_name.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.skill1desc.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.skill2text.setText(QCoreApplication.translate("MainWindow", u"Skill 2", None))
        self.skill2pic.setText("")
        self.skill2_name.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.skill2desc.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.ultimatetext.setText(QCoreApplication.translate("MainWindow", u"Ultimate", None))
        self.ultipic.setText("")
        self.Ultimatename.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.ultimatedesc.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.specialskilltext.setText(QCoreApplication.translate("MainWindow", u"Special Skill", None))
        self.specialskilldesc.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.specialskillpic.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.Specialskillname.setText(QCoreApplication.translate("MainWindow", u"None", None))
    # retranslateUi

