# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'newpage.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
    QPushButton, QScrollArea, QSizePolicy, QSpacerItem,
    QStackedWidget, QVBoxLayout, QWidget)
import resources_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1158, 711)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(0, 0, 161, 711))
        self.widget.setStyleSheet(u"QWidget{\n"
"background-color: rgb(117, 58, 175);\n"
"}\n"
"QPushButton{\n"
"background-color: rgb(71, 142, 213);\n"
"	color: rgb(255, 255, 255);\n"
"}")
        self.layoutWidget = QWidget(self.widget)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(9, 9, 150, 681))
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.layoutWidget)
        self.label.setObjectName(u"label")
        self.label.setPixmap(QPixmap(u":/imglib/mlbb.jpg"))
        self.label.setScaledContents(True)

        self.verticalLayout.addWidget(self.label)

        self.allhero = QPushButton(self.layoutWidget)
        self.allhero.setObjectName(u"allhero")
        self.allhero.setCheckable(True)
        self.allhero.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.allhero)

        self.assa = QPushButton(self.layoutWidget)
        self.assa.setObjectName(u"assa")
        icon = QIcon()
        icon.addFile(u":/imglib/Assassin_Icon.webp", QSize(), QIcon.Normal, QIcon.Off)
        self.assa.setIcon(icon)
        self.assa.setCheckable(True)
        self.assa.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.assa)

        self.tank = QPushButton(self.layoutWidget)
        self.tank.setObjectName(u"tank")
        icon1 = QIcon()
        icon1.addFile(u":/imglib/Tank_Icon.webp", QSize(), QIcon.Normal, QIcon.Off)
        self.tank.setIcon(icon1)
        self.tank.setCheckable(True)
        self.tank.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.tank)

        self.fighter = QPushButton(self.layoutWidget)
        self.fighter.setObjectName(u"fighter")
        icon2 = QIcon()
        icon2.addFile(u":/imglib/Fighter_Icon.webp", QSize(), QIcon.Normal, QIcon.Off)
        self.fighter.setIcon(icon2)
        self.fighter.setCheckable(True)
        self.fighter.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.fighter)

        self.mage = QPushButton(self.layoutWidget)
        self.mage.setObjectName(u"mage")
        icon3 = QIcon()
        icon3.addFile(u":/imglib/Mage_Icon.webp", QSize(), QIcon.Normal, QIcon.Off)
        self.mage.setIcon(icon3)
        self.mage.setCheckable(True)
        self.mage.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.mage)

        self.mm = QPushButton(self.layoutWidget)
        self.mm.setObjectName(u"mm")
        icon4 = QIcon()
        icon4.addFile(u":/imglib/Marksman_Icon.webp", QSize(), QIcon.Normal, QIcon.Off)
        self.mm.setIcon(icon4)
        self.mm.setCheckable(True)
        self.mm.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.mm)

        self.sup = QPushButton(self.layoutWidget)
        self.sup.setObjectName(u"sup")
        icon5 = QIcon()
        icon5.addFile(u":/imglib/Support_Icon.webp", QSize(), QIcon.Normal, QIcon.Off)
        self.sup.setIcon(icon5)
        self.sup.setCheckable(True)
        self.sup.setAutoExclusive(True)

        self.verticalLayout.addWidget(self.sup)

        self.verticalSpacer = QSpacerItem(20, 325, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer)

        self.cls = QPushButton(self.layoutWidget)
        self.cls.setObjectName(u"cls")
        self.cls.setCheckable(True)

        self.verticalLayout.addWidget(self.cls)

        self.widget_2 = QWidget(self.centralwidget)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(160, -20, 1001, 731))
        self.widget_2.setStyleSheet(u"QWidget{\n"
"background-color: rgb(0, 0, 255);\n"
"}")
        self.stackedWidget = QStackedWidget(self.widget_2)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(30, 40, 941, 671))
        self.stackedWidget.setFocusPolicy(Qt.StrongFocus)
        self.stackedWidget.setStyleSheet(u"\n"
"background-color: rgb(255, 58, 24);")
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.scrollArea = QScrollArea(self.page)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(10, 20, 931, 661))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 912, 1218))
        self.scrollAreaWidgetContents.setStyleSheet(u"QScrollBar:vertical{\n"
"border: none;\n"
"background-color: rgb(59,59,90);\n"
"width:14px;\n"
"margin: 15 px 0 15px 0;\n"
"border-radius: 0px;\n"
"}")
        self.verticalLayout_2 = QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.frame = QFrame(self.scrollAreaWidgetContents)
        self.frame.setObjectName(u"frame")
        self.frame.setMinimumSize(QSize(0, 1200))
        self.frame.setStyleSheet(u"background-color: rgb(255, 0, 0);")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.Saber = QPushButton(self.frame)
        self.Saber.setObjectName(u"Saber")
        self.Saber.setGeometry(QRect(20, 60, 81, 23))
        self.Saber.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Saber.setCheckable(False)
        self.Saber.setAutoExclusive(True)
        self.label_9 = QLabel(self.frame)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 0, 81, 51))
        self.label_9.setPixmap(QPixmap(u":/imglib/Saber.png"))
        self.label_9.setScaledContents(True)
        self.Karina = QPushButton(self.frame)
        self.Karina.setObjectName(u"Karina")
        self.Karina.setGeometry(QRect(130, 60, 81, 23))
        self.Karina.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Karina.setCheckable(False)
        self.Karina.setAutoExclusive(True)
        self.Alucard = QPushButton(self.frame)
        self.Alucard.setObjectName(u"Alucard")
        self.Alucard.setGeometry(QRect(240, 60, 81, 23))
        self.Alucard.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Alucard.setCheckable(False)
        self.Alucard.setAutoExclusive(True)
        self.Hayabusa = QPushButton(self.frame)
        self.Hayabusa.setObjectName(u"Hayabusa")
        self.Hayabusa.setGeometry(QRect(440, 60, 81, 23))
        self.Hayabusa.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Hayabusa.setCheckable(False)
        self.Hayabusa.setAutoExclusive(True)
        self.Fanny = QPushButton(self.frame)
        self.Fanny.setObjectName(u"Fanny")
        self.Fanny.setGeometry(QRect(340, 60, 81, 23))
        self.Fanny.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Fanny.setCheckable(False)
        self.Fanny.setAutoExclusive(True)
        self.Natalia = QPushButton(self.frame)
        self.Natalia.setObjectName(u"Natalia")
        self.Natalia.setGeometry(QRect(540, 60, 81, 23))
        self.Natalia.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Natalia.setCheckable(False)
        self.label_10 = QLabel(self.frame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(130, 0, 81, 51))
        self.label_10.setPixmap(QPixmap(u":/imglib/Karina.jpg"))
        self.label_10.setScaledContents(True)
        self.label_11 = QLabel(self.frame)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(240, 0, 81, 51))
        self.label_11.setPixmap(QPixmap(u":/imglib/Alucard.jpg"))
        self.label_11.setScaledContents(True)
        self.label_12 = QLabel(self.frame)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(340, 0, 81, 51))
        self.label_12.setPixmap(QPixmap(u":/imglib/fanny.png"))
        self.label_12.setScaledContents(True)
        self.label_13 = QLabel(self.frame)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(440, 0, 81, 51))
        self.label_13.setPixmap(QPixmap(u":/imglib/Hayabusa.webp"))
        self.label_13.setScaledContents(True)
        self.label_14 = QLabel(self.frame)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(540, 0, 81, 51))
        self.label_14.setPixmap(QPixmap(u":/imglib/natalia.webp"))
        self.label_14.setScaledContents(True)
        self.label_15 = QLabel(self.frame)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(740, 0, 81, 51))
        self.label_15.setPixmap(QPixmap(u":/imglib/Helcurt.webp"))
        self.label_15.setScaledContents(True)
        self.Helcurt = QPushButton(self.frame)
        self.Helcurt.setObjectName(u"Helcurt")
        self.Helcurt.setGeometry(QRect(740, 60, 81, 23))
        self.Helcurt.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Helcurt.setCheckable(False)
        self.label_16 = QLabel(self.frame)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(640, 0, 81, 51))
        self.label_16.setPixmap(QPixmap(u":/imglib/Lancelot.webp"))
        self.label_16.setScaledContents(True)
        self.Lancelot = QPushButton(self.frame)
        self.Lancelot.setObjectName(u"Lancelot")
        self.Lancelot.setGeometry(QRect(640, 60, 81, 23))
        self.Lancelot.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Lancelot.setCheckable(False)
        self.Gusion = QPushButton(self.frame)
        self.Gusion.setObjectName(u"Gusion")
        self.Gusion.setGeometry(QRect(20, 160, 81, 23))
        self.Gusion.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Gusion.setCheckable(False)
        self.Gusion.setAutoExclusive(True)
        self.label_17 = QLabel(self.frame)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 100, 81, 51))
        self.label_17.setPixmap(QPixmap(u":/imglib/Gusion.webp"))
        self.label_17.setScaledContents(True)
        self.label_18 = QLabel(self.frame)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(130, 100, 81, 51))
        self.label_18.setPixmap(QPixmap(u":/imglib/Hanzo.webp"))
        self.label_18.setScaledContents(True)
        self.Hanzo = QPushButton(self.frame)
        self.Hanzo.setObjectName(u"Hanzo")
        self.Hanzo.setGeometry(QRect(130, 160, 81, 23))
        self.Hanzo.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Hanzo.setCheckable(False)
        self.Hanzo.setAutoExclusive(True)
        self.Ling = QPushButton(self.frame)
        self.Ling.setObjectName(u"Ling")
        self.Ling.setGeometry(QRect(240, 160, 81, 23))
        self.Ling.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Ling.setCheckable(False)
        self.Ling.setAutoExclusive(True)
        self.label_19 = QLabel(self.frame)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(240, 100, 81, 51))
        self.label_19.setPixmap(QPixmap(u":/imglib/Ling.webp"))
        self.label_19.setScaledContents(True)
        self.Zilong = QPushButton(self.frame)
        self.Zilong.setObjectName(u"Zilong")
        self.Zilong.setGeometry(QRect(340, 160, 81, 23))
        self.Zilong.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Zilong.setCheckable(False)
        self.Zilong.setAutoExclusive(True)
        self.label_20 = QLabel(self.frame)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(340, 100, 81, 51))
        self.label_20.setPixmap(QPixmap(u":/imglib/Zilong_29.webp"))
        self.label_20.setScaledContents(True)
        self.label_21 = QLabel(self.frame)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(440, 100, 81, 51))
        self.label_21.setPixmap(QPixmap(u":/imglib/Tigreal_29.webp"))
        self.label_21.setScaledContents(True)
        self.Tig = QPushButton(self.frame)
        self.Tig.setObjectName(u"Tig")
        self.Tig.setGeometry(QRect(440, 160, 81, 23))
        self.Tig.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Tig.setCheckable(False)
        self.Tig.setAutoExclusive(True)
        self.label_22 = QLabel(self.frame)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(540, 100, 81, 51))
        self.label_22.setPixmap(QPixmap(u":/imglib/Akai_29.webp"))
        self.label_22.setScaledContents(True)
        self.Kai = QPushButton(self.frame)
        self.Kai.setObjectName(u"Kai")
        self.Kai.setGeometry(QRect(540, 160, 81, 23))
        self.Kai.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Kai.setCheckable(False)
        self.Kai.setAutoExclusive(True)
        self.Bane = QPushButton(self.frame)
        self.Bane.setObjectName(u"Bane")
        self.Bane.setGeometry(QRect(640, 160, 81, 23))
        self.Bane.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Bane.setCheckable(False)
        self.Bane.setAutoExclusive(True)
        self.label_23 = QLabel(self.frame)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(640, 100, 81, 51))
        self.label_23.setPixmap(QPixmap(u":/imglib/Bane_29.webp"))
        self.label_23.setScaledContents(True)
        self.label_54 = QLabel(self.frame)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(740, 100, 81, 51))
        self.label_54.setPixmap(QPixmap(u":/imglib/Layla_29.webp"))
        self.label_54.setScaledContents(True)
        self.Layla = QPushButton(self.frame)
        self.Layla.setObjectName(u"Layla")
        self.Layla.setGeometry(QRect(740, 160, 81, 23))
        self.Layla.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Layla.setCheckable(False)
        self.Layla.setAutoExclusive(True)
        self.Eud = QPushButton(self.frame)
        self.Eud.setObjectName(u"Eud")
        self.Eud.setGeometry(QRect(20, 270, 81, 23))
        self.Eud.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Eud.setCheckable(False)
        self.Eud.setAutoExclusive(True)
        self.label_55 = QLabel(self.frame)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(20, 210, 81, 51))
        self.label_55.setPixmap(QPixmap(u":/imglib/Eudora_29.webp"))
        self.label_55.setScaledContents(True)
        self.Rafa = QPushButton(self.frame)
        self.Rafa.setObjectName(u"Rafa")
        self.Rafa.setGeometry(QRect(130, 270, 81, 23))
        self.Rafa.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Rafa.setCheckable(False)
        self.Rafa.setAutoExclusive(True)
        self.label_56 = QLabel(self.frame)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(130, 210, 81, 51))
        self.label_56.setPixmap(QPixmap(u":/imglib/Rafaela_29.webp"))
        self.label_56.setScaledContents(True)
        self.Roger = QPushButton(self.frame)
        self.Roger.setObjectName(u"Roger")
        self.Roger.setGeometry(QRect(240, 270, 81, 23))
        self.Roger.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Roger.setCheckable(False)
        self.Roger.setAutoExclusive(True)
        self.label_57 = QLabel(self.frame)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(240, 210, 81, 51))
        self.label_57.setPixmap(QPixmap(u":/imglib/Roger_29.webp"))
        self.label_57.setScaledContents(True)
        self.Moskov = QPushButton(self.frame)
        self.Moskov.setObjectName(u"Moskov")
        self.Moskov.setGeometry(QRect(340, 270, 81, 23))
        self.Moskov.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Moskov.setCheckable(False)
        self.Moskov.setAutoExclusive(True)
        self.label_58 = QLabel(self.frame)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(340, 210, 81, 51))
        self.label_58.setPixmap(QPixmap(u":/imglib/Moskov_29.webp"))
        self.label_58.setScaledContents(True)
        self.Bruno = QPushButton(self.frame)
        self.Bruno.setObjectName(u"Bruno")
        self.Bruno.setGeometry(QRect(440, 270, 81, 23))
        self.Bruno.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Bruno.setCheckable(False)
        self.Bruno.setAutoExclusive(True)
        self.label_59 = QLabel(self.frame)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(440, 210, 81, 51))
        self.label_59.setPixmap(QPixmap(u":/imglib/Bruno_29.webp"))
        self.label_59.setScaledContents(True)
        self.Karrie = QPushButton(self.frame)
        self.Karrie.setObjectName(u"Karrie")
        self.Karrie.setGeometry(QRect(540, 270, 81, 23))
        self.Karrie.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Karrie.setCheckable(False)
        self.Karrie.setAutoExclusive(True)
        self.label_60 = QLabel(self.frame)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(540, 210, 81, 51))
        self.label_60.setPixmap(QPixmap(u":/imglib/Lost_Star_wall.webp"))
        self.label_60.setScaledContents(True)
        self.Franco = QPushButton(self.frame)
        self.Franco.setObjectName(u"Franco")
        self.Franco.setGeometry(QRect(640, 270, 81, 23))
        self.Franco.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Franco.setCheckable(False)
        self.Franco.setAutoExclusive(True)
        self.label_61 = QLabel(self.frame)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setGeometry(QRect(640, 210, 81, 51))
        self.label_61.setPixmap(QPixmap(u":/imglib/Franco_29.webp"))
        self.label_61.setScaledContents(True)
        self.label_121 = QLabel(self.frame)
        self.label_121.setObjectName(u"label_121")
        self.label_121.setGeometry(QRect(740, 210, 81, 51))
        self.label_121.setPixmap(QPixmap(u":/imglib/Ocean_Gladiator_wall.webp"))
        self.label_121.setScaledContents(True)
        self.Atlas = QPushButton(self.frame)
        self.Atlas.setObjectName(u"Atlas")
        self.Atlas.setGeometry(QRect(740, 270, 81, 23))
        self.Atlas.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Atlas.setCheckable(False)
        self.Atlas.setAutoExclusive(True)
        self.Estes = QPushButton(self.frame)
        self.Estes.setObjectName(u"Estes")
        self.Estes.setGeometry(QRect(20, 370, 81, 23))
        self.Estes.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Estes.setCheckable(False)
        self.Estes.setAutoExclusive(True)
        self.label_122 = QLabel(self.frame)
        self.label_122.setObjectName(u"label_122")
        self.label_122.setGeometry(QRect(20, 310, 81, 51))
        self.label_122.setPixmap(QPixmap(u":/imglib/Estes_29.webp"))
        self.label_122.setScaledContents(True)
        self.label_123 = QLabel(self.frame)
        self.label_123.setObjectName(u"label_123")
        self.label_123.setGeometry(QRect(130, 310, 81, 51))
        self.label_123.setPixmap(QPixmap(u":/imglib/Angela_29.webp"))
        self.label_123.setScaledContents(True)
        self.Angela = QPushButton(self.frame)
        self.Angela.setObjectName(u"Angela")
        self.Angela.setGeometry(QRect(130, 370, 81, 23))
        self.Angela.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Angela.setCheckable(False)
        self.Angela.setAutoExclusive(True)
        self.label_124 = QLabel(self.frame)
        self.label_124.setObjectName(u"label_124")
        self.label_124.setGeometry(QRect(240, 310, 81, 51))
        self.label_124.setPixmap(QPixmap(u":/imglib/Floryn_29.webp"))
        self.label_124.setScaledContents(True)
        self.Floryn = QPushButton(self.frame)
        self.Floryn.setObjectName(u"Floryn")
        self.Floryn.setGeometry(QRect(240, 370, 81, 23))
        self.Floryn.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Floryn.setCheckable(False)
        self.Floryn.setAutoExclusive(True)
        self.Valir = QPushButton(self.frame)
        self.Valir.setObjectName(u"Valir")
        self.Valir.setGeometry(QRect(340, 370, 81, 23))
        self.Valir.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Valir.setCheckable(False)
        self.Valir.setAutoExclusive(True)
        self.label_125 = QLabel(self.frame)
        self.label_125.setObjectName(u"label_125")
        self.label_125.setGeometry(QRect(340, 310, 81, 51))
        self.label_125.setPixmap(QPixmap(u":/imglib/Valir_29.webp"))
        self.label_125.setScaledContents(True)
        self.label_126 = QLabel(self.frame)
        self.label_126.setObjectName(u"label_126")
        self.label_126.setGeometry(QRect(440, 310, 81, 51))
        self.label_126.setPixmap(QPixmap(u":/imglib/Vexana_29.webp"))
        self.label_126.setScaledContents(True)
        self.Vex = QPushButton(self.frame)
        self.Vex.setObjectName(u"Vex")
        self.Vex.setGeometry(QRect(440, 370, 81, 23))
        self.Vex.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Vex.setCheckable(False)
        self.Vex.setAutoExclusive(True)
        self.label_127 = QLabel(self.frame)
        self.label_127.setObjectName(u"label_127")
        self.label_127.setGeometry(QRect(540, 310, 81, 51))
        self.label_127.setPixmap(QPixmap(u":/imglib/Nana_Wall.webp"))
        self.label_127.setScaledContents(True)
        self.Nana = QPushButton(self.frame)
        self.Nana.setObjectName(u"Nana")
        self.Nana.setGeometry(QRect(540, 370, 81, 23))
        self.Nana.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Nana.setCheckable(False)
        self.Nana.setAutoExclusive(True)

        self.verticalLayout_2.addWidget(self.frame)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.page)
        self.assaspage = QWidget()
        self.assaspage.setObjectName(u"assaspage")
        self.label_3 = QLabel(self.assaspage)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(310, 40, 341, 41))
        font = QFont()
        font.setFamilies([u"Sitka Banner Semibold"])
        font.setPointSize(19)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.label_3.setAlignment(Qt.AlignCenter)
        self.label_8 = QLabel(self.assaspage)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(40, 70, 71, 51))
        self.label_8.setPixmap(QPixmap(u":/Saber.png"))
        self.label_8.setScaledContents(True)
        self.label_39 = QLabel(self.assaspage)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(430, 110, 81, 51))
        self.label_39.setPixmap(QPixmap(u":/imglib/Alucard.jpg"))
        self.label_39.setScaledContents(True)
        self.label_40 = QLabel(self.assaspage)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(650, 110, 81, 51))
        self.label_40.setPixmap(QPixmap(u":/imglib/Hayabusa.webp"))
        self.label_40.setScaledContents(True)
        self.Fanny_3 = QPushButton(self.assaspage)
        self.Fanny_3.setObjectName(u"Fanny_3")
        self.Fanny_3.setGeometry(QRect(540, 180, 81, 23))
        self.Fanny_3.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Fanny_3.setCheckable(False)
        self.Fanny_3.setAutoExclusive(True)
        self.Hayabusa_3 = QPushButton(self.assaspage)
        self.Hayabusa_3.setObjectName(u"Hayabusa_3")
        self.Hayabusa_3.setGeometry(QRect(650, 180, 81, 23))
        self.Hayabusa_3.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Hayabusa_3.setCheckable(False)
        self.Hayabusa_3.setAutoExclusive(True)
        self.Karina_3 = QPushButton(self.assaspage)
        self.Karina_3.setObjectName(u"Karina_3")
        self.Karina_3.setGeometry(QRect(320, 180, 81, 23))
        self.Karina_3.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Karina_3.setCheckable(False)
        self.Karina_3.setAutoExclusive(True)
        self.label_41 = QLabel(self.assaspage)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(540, 110, 81, 51))
        self.label_41.setPixmap(QPixmap(u":/imglib/fanny.png"))
        self.label_41.setScaledContents(True)
        self.Alucard_3 = QPushButton(self.assaspage)
        self.Alucard_3.setObjectName(u"Alucard_3")
        self.Alucard_3.setGeometry(QRect(430, 180, 81, 23))
        self.Alucard_3.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Alucard_3.setCheckable(False)
        self.Alucard_3.setAutoExclusive(True)
        self.label_42 = QLabel(self.assaspage)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(320, 110, 81, 51))
        self.label_42.setPixmap(QPixmap(u":/imglib/Karina.jpg"))
        self.label_42.setScaledContents(True)
        self.label_43 = QLabel(self.assaspage)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(210, 110, 81, 51))
        self.label_43.setPixmap(QPixmap(u":/imglib/Saber.png"))
        self.label_43.setScaledContents(True)
        self.Saber_3 = QPushButton(self.assaspage)
        self.Saber_3.setObjectName(u"Saber_3")
        self.Saber_3.setGeometry(QRect(210, 180, 81, 23))
        self.Saber_3.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Saber_3.setCheckable(False)
        self.Saber_3.setAutoExclusive(True)
        self.stackedWidget.addWidget(self.assaspage)
        self.tankspage = QWidget()
        self.tankspage.setObjectName(u"tankspage")
        self.label_4 = QLabel(self.tankspage)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(300, 40, 341, 41))
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.label_4.setAlignment(Qt.AlignCenter)
        self.Hanzo_3 = QPushButton(self.tankspage)
        self.Hanzo_3.setObjectName(u"Hanzo_3")
        self.Hanzo_3.setGeometry(QRect(190, 180, 81, 23))
        self.Hanzo_3.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Hanzo_3.setCheckable(False)
        self.Hanzo_3.setAutoExclusive(True)
        self.label_50 = QLabel(self.tankspage)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(190, 110, 81, 51))
        self.label_50.setPixmap(QPixmap(u":/imglib/Hanzo.webp"))
        self.label_50.setScaledContents(True)
        self.label_51 = QLabel(self.tankspage)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(310, 110, 81, 51))
        self.label_51.setPixmap(QPixmap(u":/imglib/Tigreal_29.webp"))
        self.label_51.setScaledContents(True)
        self.Tig_3 = QPushButton(self.tankspage)
        self.Tig_3.setObjectName(u"Tig_3")
        self.Tig_3.setGeometry(QRect(310, 180, 81, 23))
        self.Tig_3.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Tig_3.setCheckable(False)
        self.Tig_3.setAutoExclusive(True)
        self.Kai_3 = QPushButton(self.tankspage)
        self.Kai_3.setObjectName(u"Kai_3")
        self.Kai_3.setGeometry(QRect(430, 180, 81, 23))
        self.Kai_3.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Kai_3.setCheckable(False)
        self.Kai_3.setAutoExclusive(True)
        self.label_52 = QLabel(self.tankspage)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(430, 110, 81, 51))
        self.label_52.setPixmap(QPixmap(u":/imglib/Akai_29.webp"))
        self.label_52.setScaledContents(True)
        self.label_117 = QLabel(self.tankspage)
        self.label_117.setObjectName(u"label_117")
        self.label_117.setGeometry(QRect(540, 110, 81, 51))
        self.label_117.setPixmap(QPixmap(u":/imglib/Franco_29.webp"))
        self.label_117.setScaledContents(True)
        self.Franco_3 = QPushButton(self.tankspage)
        self.Franco_3.setObjectName(u"Franco_3")
        self.Franco_3.setGeometry(QRect(540, 180, 81, 23))
        self.Franco_3.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Franco_3.setCheckable(False)
        self.Franco_3.setAutoExclusive(True)
        self.Atlas_2 = QPushButton(self.tankspage)
        self.Atlas_2.setObjectName(u"Atlas_2")
        self.Atlas_2.setGeometry(QRect(660, 180, 81, 23))
        self.Atlas_2.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Atlas_2.setCheckable(False)
        self.Atlas_2.setAutoExclusive(True)
        self.label_128 = QLabel(self.tankspage)
        self.label_128.setObjectName(u"label_128")
        self.label_128.setGeometry(QRect(660, 110, 81, 51))
        self.label_128.setPixmap(QPixmap(u":/imglib/Ocean_Gladiator_wall.webp"))
        self.label_128.setScaledContents(True)
        self.stackedWidget.addWidget(self.tankspage)
        self.fighterspage = QWidget()
        self.fighterspage.setObjectName(u"fighterspage")
        self.label_5 = QLabel(self.fighterspage)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(300, 40, 341, 41))
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_44 = QLabel(self.fighterspage)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(210, 100, 81, 51))
        self.label_44.setPixmap(QPixmap(u":/imglib/Lancelot.webp"))
        self.label_44.setScaledContents(True)
        self.Gusion_3 = QPushButton(self.fighterspage)
        self.Gusion_3.setObjectName(u"Gusion_3")
        self.Gusion_3.setGeometry(QRect(610, 170, 81, 23))
        self.Gusion_3.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Gusion_3.setCheckable(False)
        self.Gusion_3.setAutoExclusive(True)
        self.label_45 = QLabel(self.fighterspage)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(310, 100, 81, 51))
        self.label_45.setPixmap(QPixmap(u":/imglib/Ling.webp"))
        self.label_45.setScaledContents(True)
        self.Zilong_3 = QPushButton(self.fighterspage)
        self.Zilong_3.setObjectName(u"Zilong_3")
        self.Zilong_3.setGeometry(QRect(410, 170, 81, 23))
        self.Zilong_3.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Zilong_3.setCheckable(False)
        self.Zilong_3.setAutoExclusive(True)
        self.label_46 = QLabel(self.fighterspage)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(410, 100, 81, 51))
        self.label_46.setPixmap(QPixmap(u":/imglib/Zilong_29.webp"))
        self.label_46.setScaledContents(True)
        self.Lancelot_3 = QPushButton(self.fighterspage)
        self.Lancelot_3.setObjectName(u"Lancelot_3")
        self.Lancelot_3.setGeometry(QRect(210, 170, 81, 23))
        self.Lancelot_3.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Lancelot_3.setCheckable(False)
        self.label_48 = QLabel(self.fighterspage)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(510, 100, 81, 51))
        self.label_48.setPixmap(QPixmap(u":/imglib/Helcurt.webp"))
        self.label_48.setScaledContents(True)
        self.Ling_3 = QPushButton(self.fighterspage)
        self.Ling_3.setObjectName(u"Ling_3")
        self.Ling_3.setGeometry(QRect(310, 170, 81, 23))
        self.Ling_3.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Ling_3.setCheckable(False)
        self.Ling_3.setAutoExclusive(True)
        self.Helcurt_3 = QPushButton(self.fighterspage)
        self.Helcurt_3.setObjectName(u"Helcurt_3")
        self.Helcurt_3.setGeometry(QRect(510, 170, 81, 23))
        self.Helcurt_3.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Helcurt_3.setCheckable(False)
        self.label_49 = QLabel(self.fighterspage)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(610, 100, 81, 51))
        self.label_49.setPixmap(QPixmap(u":/imglib/Gusion.webp"))
        self.label_49.setScaledContents(True)
        self.stackedWidget.addWidget(self.fighterspage)
        self.magepage = QWidget()
        self.magepage.setObjectName(u"magepage")
        self.label_6 = QLabel(self.magepage)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(300, 50, 341, 41))
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.label_6.setAlignment(Qt.AlignCenter)
        self.Bane_2 = QPushButton(self.magepage)
        self.Bane_2.setObjectName(u"Bane_2")
        self.Bane_2.setGeometry(QRect(230, 170, 81, 23))
        self.Bane_2.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Bane_2.setCheckable(False)
        self.Bane_2.setAutoExclusive(True)
        self.label_53 = QLabel(self.magepage)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(230, 110, 81, 51))
        self.label_53.setPixmap(QPixmap(u":/imglib/Bane_29.webp"))
        self.label_53.setScaledContents(True)
        self.Eud_3 = QPushButton(self.magepage)
        self.Eud_3.setObjectName(u"Eud_3")
        self.Eud_3.setGeometry(QRect(340, 170, 81, 23))
        self.Eud_3.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Eud_3.setCheckable(False)
        self.Eud_3.setAutoExclusive(True)
        self.label_119 = QLabel(self.magepage)
        self.label_119.setObjectName(u"label_119")
        self.label_119.setGeometry(QRect(340, 110, 81, 51))
        self.label_119.setPixmap(QPixmap(u":/imglib/Eudora_29.webp"))
        self.label_119.setScaledContents(True)
        self.label_129 = QLabel(self.magepage)
        self.label_129.setObjectName(u"label_129")
        self.label_129.setGeometry(QRect(650, 110, 81, 51))
        self.label_129.setPixmap(QPixmap(u":/imglib/Nana_Wall.webp"))
        self.label_129.setScaledContents(True)
        self.label_130 = QLabel(self.magepage)
        self.label_130.setObjectName(u"label_130")
        self.label_130.setGeometry(QRect(450, 110, 81, 51))
        self.label_130.setPixmap(QPixmap(u":/imglib/Valir_29.webp"))
        self.label_130.setScaledContents(True)
        self.label_131 = QLabel(self.magepage)
        self.label_131.setObjectName(u"label_131")
        self.label_131.setGeometry(QRect(550, 110, 81, 51))
        self.label_131.setPixmap(QPixmap(u":/imglib/Vexana_29.webp"))
        self.label_131.setScaledContents(True)
        self.Vex_2 = QPushButton(self.magepage)
        self.Vex_2.setObjectName(u"Vex_2")
        self.Vex_2.setGeometry(QRect(550, 170, 81, 23))
        self.Vex_2.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Vex_2.setCheckable(False)
        self.Vex_2.setAutoExclusive(True)
        self.Nana_2 = QPushButton(self.magepage)
        self.Nana_2.setObjectName(u"Nana_2")
        self.Nana_2.setGeometry(QRect(650, 170, 81, 23))
        self.Nana_2.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Nana_2.setCheckable(False)
        self.Nana_2.setAutoExclusive(True)
        self.Valir_2 = QPushButton(self.magepage)
        self.Valir_2.setObjectName(u"Valir_2")
        self.Valir_2.setGeometry(QRect(450, 170, 81, 23))
        self.Valir_2.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Valir_2.setCheckable(False)
        self.Valir_2.setAutoExclusive(True)
        self.stackedWidget.addWidget(self.magepage)
        self.mmpage = QWidget()
        self.mmpage.setObjectName(u"mmpage")
        self.label_7 = QLabel(self.mmpage)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(300, 50, 341, 41))
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.label_7.setAlignment(Qt.AlignCenter)
        self.Layla_2 = QPushButton(self.mmpage)
        self.Layla_2.setObjectName(u"Layla_2")
        self.Layla_2.setGeometry(QRect(210, 170, 81, 23))
        self.Layla_2.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Layla_2.setCheckable(False)
        self.Layla_2.setAutoExclusive(True)
        self.label_62 = QLabel(self.mmpage)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setGeometry(QRect(610, 110, 81, 51))
        self.label_62.setPixmap(QPixmap(u":/imglib/Lost_Star_wall.webp"))
        self.label_62.setScaledContents(True)
        self.Bruno_2 = QPushButton(self.mmpage)
        self.Bruno_2.setObjectName(u"Bruno_2")
        self.Bruno_2.setGeometry(QRect(510, 170, 81, 23))
        self.Bruno_2.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Bruno_2.setCheckable(False)
        self.Bruno_2.setAutoExclusive(True)
        self.label_63 = QLabel(self.mmpage)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setGeometry(QRect(510, 110, 81, 51))
        self.label_63.setPixmap(QPixmap(u":/imglib/Bruno_29.webp"))
        self.label_63.setScaledContents(True)
        self.label_64 = QLabel(self.mmpage)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setGeometry(QRect(210, 110, 81, 51))
        self.label_64.setPixmap(QPixmap(u":/imglib/Layla_29.webp"))
        self.label_64.setScaledContents(True)
        self.Roger_2 = QPushButton(self.mmpage)
        self.Roger_2.setObjectName(u"Roger_2")
        self.Roger_2.setGeometry(QRect(310, 170, 81, 23))
        self.Roger_2.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Roger_2.setCheckable(False)
        self.Roger_2.setAutoExclusive(True)
        self.label_65 = QLabel(self.mmpage)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setGeometry(QRect(310, 110, 81, 51))
        self.label_65.setPixmap(QPixmap(u":/imglib/Roger_29.webp"))
        self.label_65.setScaledContents(True)
        self.Moskov_2 = QPushButton(self.mmpage)
        self.Moskov_2.setObjectName(u"Moskov_2")
        self.Moskov_2.setGeometry(QRect(410, 170, 81, 23))
        self.Moskov_2.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Moskov_2.setCheckable(False)
        self.Moskov_2.setAutoExclusive(True)
        self.Karrie_2 = QPushButton(self.mmpage)
        self.Karrie_2.setObjectName(u"Karrie_2")
        self.Karrie_2.setGeometry(QRect(610, 170, 81, 23))
        self.Karrie_2.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Karrie_2.setCheckable(False)
        self.Karrie_2.setAutoExclusive(True)
        self.label_66 = QLabel(self.mmpage)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setGeometry(QRect(410, 110, 81, 51))
        self.label_66.setPixmap(QPixmap(u":/imglib/Moskov_29.webp"))
        self.label_66.setScaledContents(True)
        self.stackedWidget.addWidget(self.mmpage)
        self.supportpage = QWidget()
        self.supportpage.setObjectName(u"supportpage")
        self.label_2 = QLabel(self.supportpage)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(310, 50, 341, 41))
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(u"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 255);")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.Natalia_6 = QPushButton(self.supportpage)
        self.Natalia_6.setObjectName(u"Natalia_6")
        self.Natalia_6.setGeometry(QRect(220, 170, 81, 23))
        self.Natalia_6.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Natalia_6.setCheckable(False)
        self.label_118 = QLabel(self.supportpage)
        self.label_118.setObjectName(u"label_118")
        self.label_118.setGeometry(QRect(220, 110, 81, 51))
        self.label_118.setPixmap(QPixmap(u":/imglib/natalia.webp"))
        self.label_118.setScaledContents(True)
        self.Rafa_3 = QPushButton(self.supportpage)
        self.Rafa_3.setObjectName(u"Rafa_3")
        self.Rafa_3.setGeometry(QRect(320, 170, 81, 23))
        self.Rafa_3.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Rafa_3.setCheckable(False)
        self.Rafa_3.setAutoExclusive(True)
        self.label_120 = QLabel(self.supportpage)
        self.label_120.setObjectName(u"label_120")
        self.label_120.setGeometry(QRect(320, 110, 81, 51))
        self.label_120.setPixmap(QPixmap(u":/imglib/Rafaela_29.webp"))
        self.label_120.setScaledContents(True)
        self.label_195 = QLabel(self.supportpage)
        self.label_195.setObjectName(u"label_195")
        self.label_195.setGeometry(QRect(530, 110, 81, 51))
        self.label_195.setPixmap(QPixmap(u":/imglib/Angela_29.webp"))
        self.label_195.setScaledContents(True)
        self.label_196 = QLabel(self.supportpage)
        self.label_196.setObjectName(u"label_196")
        self.label_196.setGeometry(QRect(420, 110, 81, 51))
        self.label_196.setPixmap(QPixmap(u":/imglib/Estes_29.webp"))
        self.label_196.setScaledContents(True)
        self.Floryn_3 = QPushButton(self.supportpage)
        self.Floryn_3.setObjectName(u"Floryn_3")
        self.Floryn_3.setGeometry(QRect(640, 170, 81, 23))
        self.Floryn_3.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Floryn_3.setCheckable(False)
        self.Floryn_3.setAutoExclusive(True)
        self.label_197 = QLabel(self.supportpage)
        self.label_197.setObjectName(u"label_197")
        self.label_197.setGeometry(QRect(640, 110, 81, 51))
        self.label_197.setPixmap(QPixmap(u":/imglib/Floryn_29.webp"))
        self.label_197.setScaledContents(True)
        self.Estes_3 = QPushButton(self.supportpage)
        self.Estes_3.setObjectName(u"Estes_3")
        self.Estes_3.setGeometry(QRect(420, 170, 81, 23))
        self.Estes_3.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Estes_3.setCheckable(False)
        self.Estes_3.setAutoExclusive(True)
        self.Angela_3 = QPushButton(self.supportpage)
        self.Angela_3.setObjectName(u"Angela_3")
        self.Angela_3.setGeometry(QRect(530, 170, 81, 23))
        self.Angela_3.setStyleSheet(u"background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.Angela_3.setCheckable(False)
        self.Angela_3.setAutoExclusive(True)
        self.stackedWidget.addWidget(self.supportpage)
        self.saberpage = QWidget()
        self.saberpage.setObjectName(u"saberpage")
        self.widget_3 = QWidget(self.saberpage)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(10, 20, 921, 651))
        self.widget_3.setStyleSheet(u"background-color: rgb(149, 0, 149);")
        self.heropic = QLabel(self.widget_3)
        self.heropic.setObjectName(u"heropic")
        self.heropic.setGeometry(QRect(30, 10, 341, 191))
        self.heropic.setPixmap(QPixmap(u":/Saber.png"))
        self.heropic.setScaledContents(True)
        self.heropic.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.Passive_name_label = QLabel(self.widget_3)
        self.Passive_name_label.setObjectName(u"Passive_name_label")
        self.Passive_name_label.setGeometry(QRect(90, 210, 111, 21))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        font1.setUnderline(True)
        self.Passive_name_label.setFont(font1)
        self.Passive_name_label.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.Passive_name_label.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.Passivelabel = QLabel(self.widget_3)
        self.Passivelabel.setObjectName(u"Passivelabel")
        self.Passivelabel.setGeometry(QRect(20, 200, 61, 21))
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        self.Passivelabel.setFont(font2)
        self.Passivelabel.setStyleSheet(u"color: rgb(85, 255, 127);")
        self.Passivelabel.setOpenExternalLinks(False)
        self.Passivelabel.setTextInteractionFlags(Qt.LinksAccessibleByMouse|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.passivepic = QLabel(self.widget_3)
        self.passivepic.setObjectName(u"passivepic")
        self.passivepic.setGeometry(QRect(20, 220, 47, 51))
        self.passivepic.setPixmap(QPixmap(u":/EnemyBane.png"))
        self.passivepic.setScaledContents(True)
        self.passivepic.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.passivedesc = QLabel(self.widget_3)
        self.passivedesc.setObjectName(u"passivedesc")
        self.passivedesc.setGeometry(QRect(80, 240, 811, 31))
        self.passivedesc.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.passivedesc.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.passivedesc.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.skill1text = QLabel(self.widget_3)
        self.skill1text.setObjectName(u"skill1text")
        self.skill1text.setGeometry(QRect(20, 280, 51, 16))
        self.skill1text.setFont(font2)
        self.skill1text.setStyleSheet(u"color: rgb(85, 255, 127);")
        self.skill1pic = QLabel(self.widget_3)
        self.skill1pic.setObjectName(u"skill1pic")
        self.skill1pic.setGeometry(QRect(20, 300, 51, 51))
        self.skill1pic.setPixmap(QPixmap(u":/Orbiting_Swords.png"))
        self.skill1pic.setScaledContents(True)
        self.skill1pic.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.skill1_name = QLabel(self.widget_3)
        self.skill1_name.setObjectName(u"skill1_name")
        self.skill1_name.setGeometry(QRect(90, 290, 131, 16))
        self.skill1_name.setFont(font1)
        self.skill1_name.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.skill1_name.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.skill1desc = QLabel(self.widget_3)
        self.skill1desc.setObjectName(u"skill1desc")
        self.skill1desc.setGeometry(QRect(90, 310, 811, 71))
        self.skill1desc.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.skill1desc.setWordWrap(True)
        self.skill1desc.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.skill2text = QLabel(self.widget_3)
        self.skill2text.setObjectName(u"skill2text")
        self.skill2text.setGeometry(QRect(20, 380, 61, 21))
        self.skill2text.setFont(font2)
        self.skill2text.setStyleSheet(u"color: rgb(85, 255, 127);")
        self.skill2text.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.skill2pic = QLabel(self.widget_3)
        self.skill2pic.setObjectName(u"skill2pic")
        self.skill2pic.setGeometry(QRect(20, 410, 51, 51))
        self.skill2pic.setPixmap(QPixmap(u":/Charge.png"))
        self.skill2pic.setScaledContents(True)
        self.skill2pic.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.skill2_name = QLabel(self.widget_3)
        self.skill2_name.setObjectName(u"skill2_name")
        self.skill2_name.setGeometry(QRect(90, 390, 131, 21))
        self.skill2_name.setFont(font1)
        self.skill2_name.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.skill2_name.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.skill2desc = QLabel(self.widget_3)
        self.skill2desc.setObjectName(u"skill2desc")
        self.skill2desc.setGeometry(QRect(90, 420, 641, 51))
        self.skill2desc.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.skill2desc.setWordWrap(True)
        self.skill2desc.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.ultimatetext = QLabel(self.widget_3)
        self.ultimatetext.setObjectName(u"ultimatetext")
        self.ultimatetext.setGeometry(QRect(20, 550, 71, 21))
        self.ultimatetext.setFont(font2)
        self.ultimatetext.setStyleSheet(u"color: rgb(85, 255, 127);")
        self.ultimatetext.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.ultipic = QLabel(self.widget_3)
        self.ultipic.setObjectName(u"ultipic")
        self.ultipic.setGeometry(QRect(30, 580, 51, 51))
        self.ultipic.setPixmap(QPixmap(u":/Triple_Sweep.png"))
        self.ultipic.setScaledContents(True)
        self.ultipic.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.Ultimatename = QLabel(self.widget_3)
        self.Ultimatename.setObjectName(u"Ultimatename")
        self.Ultimatename.setGeometry(QRect(100, 555, 151, 21))
        self.Ultimatename.setFont(font1)
        self.Ultimatename.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.Ultimatename.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.ultimatedesc = QLabel(self.widget_3)
        self.ultimatedesc.setObjectName(u"ultimatedesc")
        self.ultimatedesc.setGeometry(QRect(100, 580, 641, 51))
        self.ultimatedesc.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.ultimatedesc.setWordWrap(True)
        self.ultimatedesc.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.specialskilltext = QLabel(self.widget_3)
        self.specialskilltext.setObjectName(u"specialskilltext")
        self.specialskilltext.setGeometry(QRect(0, 480, 111, 16))
        self.specialskilltext.setFont(font2)
        self.specialskilltext.setStyleSheet(u"color: rgb(85, 255, 127);")
        self.specialskilldesc = QLabel(self.widget_3)
        self.specialskilldesc.setObjectName(u"specialskilldesc")
        self.specialskilldesc.setGeometry(QRect(110, 510, 641, 31))
        self.specialskilldesc.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.specialskilldesc.setWordWrap(True)
        self.specialskilldesc.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.specialskillpic = QLabel(self.widget_3)
        self.specialskillpic.setObjectName(u"specialskillpic")
        self.specialskillpic.setGeometry(QRect(30, 510, 47, 14))
        self.specialskillpic.setStyleSheet(u"background-color: rgb(255, 170, 255);")
        self.specialskillpic.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.Specialskillname = QLabel(self.widget_3)
        self.Specialskillname.setObjectName(u"Specialskillname")
        self.Specialskillname.setGeometry(QRect(110, 480, 91, 16))
        self.Specialskillname.setFont(font1)
        self.Specialskillname.setStyleSheet(u"color: rgb(255, 255, 255);")
        self.Specialskillname.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse|Qt.TextBrowserInteraction|Qt.TextEditable|Qt.TextEditorInteraction|Qt.TextSelectableByKeyboard|Qt.TextSelectableByMouse)
        self.stackedWidget.addWidget(self.saberpage)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.cls.clicked["bool"].connect(MainWindow.close)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label.setText("")
        self.allhero.setText(QCoreApplication.translate("MainWindow", u"All ", None))
        self.assa.setText(QCoreApplication.translate("MainWindow", u"Assassins", None))
        self.tank.setText(QCoreApplication.translate("MainWindow", u"Tank", None))
        self.fighter.setText(QCoreApplication.translate("MainWindow", u"Fighter", None))
        self.mage.setText(QCoreApplication.translate("MainWindow", u"Mage", None))
        self.mm.setText(QCoreApplication.translate("MainWindow", u"Marksman", None))
        self.sup.setText(QCoreApplication.translate("MainWindow", u"Support", None))
        self.cls.setText(QCoreApplication.translate("MainWindow", u"Close", None))
#if QT_CONFIG(accessibility)
        self.Saber.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Saber.setText(QCoreApplication.translate("MainWindow", u"Saber", None))
        self.label_9.setText("")
        self.Karina.setText(QCoreApplication.translate("MainWindow", u"Karina", None))
        self.Alucard.setText(QCoreApplication.translate("MainWindow", u"Alucard", None))
        self.Hayabusa.setText(QCoreApplication.translate("MainWindow", u"Hayabusa", None))
        self.Fanny.setText(QCoreApplication.translate("MainWindow", u"Fanny", None))
        self.Natalia.setText(QCoreApplication.translate("MainWindow", u"Natalia", None))
        self.label_10.setText("")
        self.label_11.setText("")
        self.label_12.setText("")
        self.label_13.setText("")
        self.label_14.setText("")
        self.label_15.setText("")
        self.Helcurt.setText(QCoreApplication.translate("MainWindow", u"Helcurt", None))
        self.label_16.setText("")
        self.Lancelot.setText(QCoreApplication.translate("MainWindow", u"Lancelot", None))
#if QT_CONFIG(accessibility)
        self.Gusion.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Gusion.setText(QCoreApplication.translate("MainWindow", u"Gusion", None))
        self.label_17.setText("")
        self.label_18.setText("")
#if QT_CONFIG(accessibility)
        self.Hanzo.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Hanzo.setText(QCoreApplication.translate("MainWindow", u"Hanzo", None))
#if QT_CONFIG(accessibility)
        self.Ling.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Ling.setText(QCoreApplication.translate("MainWindow", u"Ling", None))
        self.label_19.setText("")
#if QT_CONFIG(accessibility)
        self.Zilong.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Zilong.setText(QCoreApplication.translate("MainWindow", u"Zilong", None))
        self.label_20.setText("")
        self.label_21.setText("")
#if QT_CONFIG(accessibility)
        self.Tig.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Tig.setText(QCoreApplication.translate("MainWindow", u"Tigreal", None))
        self.label_22.setText("")
#if QT_CONFIG(accessibility)
        self.Kai.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Kai.setText(QCoreApplication.translate("MainWindow", u"Akai", None))
#if QT_CONFIG(accessibility)
        self.Bane.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Bane.setText(QCoreApplication.translate("MainWindow", u"Bane", None))
        self.label_23.setText("")
        self.label_54.setText("")
#if QT_CONFIG(accessibility)
        self.Layla.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Layla.setText(QCoreApplication.translate("MainWindow", u"Layla", None))
#if QT_CONFIG(accessibility)
        self.Eud.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Eud.setText(QCoreApplication.translate("MainWindow", u"Eudora", None))
        self.label_55.setText("")
#if QT_CONFIG(accessibility)
        self.Rafa.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Rafa.setText(QCoreApplication.translate("MainWindow", u"Rafaela", None))
        self.label_56.setText("")
#if QT_CONFIG(accessibility)
        self.Roger.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Roger.setText(QCoreApplication.translate("MainWindow", u"Roger", None))
        self.label_57.setText("")
#if QT_CONFIG(accessibility)
        self.Moskov.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Moskov.setText(QCoreApplication.translate("MainWindow", u"Moskov", None))
        self.label_58.setText("")
#if QT_CONFIG(accessibility)
        self.Bruno.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Bruno.setText(QCoreApplication.translate("MainWindow", u"Bruno", None))
        self.label_59.setText("")
#if QT_CONFIG(accessibility)
        self.Karrie.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Karrie.setText(QCoreApplication.translate("MainWindow", u"Karrie", None))
        self.label_60.setText("")
#if QT_CONFIG(accessibility)
        self.Franco.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Franco.setText(QCoreApplication.translate("MainWindow", u"Franco", None))
        self.label_61.setText("")
        self.label_121.setText("")
#if QT_CONFIG(accessibility)
        self.Atlas.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Atlas.setText(QCoreApplication.translate("MainWindow", u"Atlas", None))
#if QT_CONFIG(accessibility)
        self.Estes.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Estes.setText(QCoreApplication.translate("MainWindow", u"Estes", None))
        self.label_122.setText("")
        self.label_123.setText("")
#if QT_CONFIG(accessibility)
        self.Angela.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Angela.setText(QCoreApplication.translate("MainWindow", u"Angela", None))
        self.label_124.setText("")
#if QT_CONFIG(accessibility)
        self.Floryn.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Floryn.setText(QCoreApplication.translate("MainWindow", u"Floryn", None))
#if QT_CONFIG(accessibility)
        self.Valir.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Valir.setText(QCoreApplication.translate("MainWindow", u"Valir", None))
        self.label_125.setText("")
        self.label_126.setText("")
#if QT_CONFIG(accessibility)
        self.Vex.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Vex.setText(QCoreApplication.translate("MainWindow", u"Vexana", None))
        self.label_127.setText("")
#if QT_CONFIG(accessibility)
        self.Nana.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Nana.setText(QCoreApplication.translate("MainWindow", u"Nana", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Assassins", None))
        self.label_8.setText("")
        self.label_39.setText("")
        self.label_40.setText("")
        self.Fanny_3.setText(QCoreApplication.translate("MainWindow", u"Fanny", None))
        self.Hayabusa_3.setText(QCoreApplication.translate("MainWindow", u"Hayabusa", None))
        self.Karina_3.setText(QCoreApplication.translate("MainWindow", u"Karina", None))
        self.label_41.setText("")
        self.Alucard_3.setText(QCoreApplication.translate("MainWindow", u"Alucard", None))
        self.label_42.setText("")
        self.label_43.setText("")
#if QT_CONFIG(accessibility)
        self.Saber_3.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Saber_3.setText(QCoreApplication.translate("MainWindow", u"Saber", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Tanks", None))
#if QT_CONFIG(accessibility)
        self.Hanzo_3.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Hanzo_3.setText(QCoreApplication.translate("MainWindow", u"Hanzo", None))
        self.label_50.setText("")
        self.label_51.setText("")
#if QT_CONFIG(accessibility)
        self.Tig_3.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Tig_3.setText(QCoreApplication.translate("MainWindow", u"Tigreal", None))
#if QT_CONFIG(accessibility)
        self.Kai_3.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Kai_3.setText(QCoreApplication.translate("MainWindow", u"Akai", None))
        self.label_52.setText("")
        self.label_117.setText("")
#if QT_CONFIG(accessibility)
        self.Franco_3.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Franco_3.setText(QCoreApplication.translate("MainWindow", u"Franco", None))
#if QT_CONFIG(accessibility)
        self.Atlas_2.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Atlas_2.setText(QCoreApplication.translate("MainWindow", u"Atlas", None))
        self.label_128.setText("")
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Fighters", None))
        self.label_44.setText("")
#if QT_CONFIG(accessibility)
        self.Gusion_3.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Gusion_3.setText(QCoreApplication.translate("MainWindow", u"Gusion", None))
        self.label_45.setText("")
#if QT_CONFIG(accessibility)
        self.Zilong_3.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Zilong_3.setText(QCoreApplication.translate("MainWindow", u"Zilong", None))
        self.label_46.setText("")
        self.Lancelot_3.setText(QCoreApplication.translate("MainWindow", u"Lancelot", None))
        self.label_48.setText("")
#if QT_CONFIG(accessibility)
        self.Ling_3.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Ling_3.setText(QCoreApplication.translate("MainWindow", u"Ling", None))
        self.Helcurt_3.setText(QCoreApplication.translate("MainWindow", u"Helcurt", None))
        self.label_49.setText("")
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Mage", None))
#if QT_CONFIG(accessibility)
        self.Bane_2.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Bane_2.setText(QCoreApplication.translate("MainWindow", u"Bane", None))
        self.label_53.setText("")
#if QT_CONFIG(accessibility)
        self.Eud_3.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Eud_3.setText(QCoreApplication.translate("MainWindow", u"Eudora", None))
        self.label_119.setText("")
        self.label_129.setText("")
        self.label_130.setText("")
        self.label_131.setText("")
#if QT_CONFIG(accessibility)
        self.Vex_2.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Vex_2.setText(QCoreApplication.translate("MainWindow", u"Vexana", None))
#if QT_CONFIG(accessibility)
        self.Nana_2.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Nana_2.setText(QCoreApplication.translate("MainWindow", u"Nana", None))
#if QT_CONFIG(accessibility)
        self.Valir_2.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Valir_2.setText(QCoreApplication.translate("MainWindow", u"Valir", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Marksman", None))
#if QT_CONFIG(accessibility)
        self.Layla_2.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Layla_2.setText(QCoreApplication.translate("MainWindow", u"Layla", None))
        self.label_62.setText("")
#if QT_CONFIG(accessibility)
        self.Bruno_2.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Bruno_2.setText(QCoreApplication.translate("MainWindow", u"Bruno", None))
        self.label_63.setText("")
        self.label_64.setText("")
#if QT_CONFIG(accessibility)
        self.Roger_2.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Roger_2.setText(QCoreApplication.translate("MainWindow", u"Roger", None))
        self.label_65.setText("")
#if QT_CONFIG(accessibility)
        self.Moskov_2.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Moskov_2.setText(QCoreApplication.translate("MainWindow", u"Moskov", None))
#if QT_CONFIG(accessibility)
        self.Karrie_2.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Karrie_2.setText(QCoreApplication.translate("MainWindow", u"Karrie", None))
        self.label_66.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Supports", None))
        self.Natalia_6.setText(QCoreApplication.translate("MainWindow", u"Natalia", None))
        self.label_118.setText("")
#if QT_CONFIG(accessibility)
        self.Rafa_3.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Rafa_3.setText(QCoreApplication.translate("MainWindow", u"Rafaela", None))
        self.label_120.setText("")
        self.label_195.setText("")
        self.label_196.setText("")
#if QT_CONFIG(accessibility)
        self.Floryn_3.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Floryn_3.setText(QCoreApplication.translate("MainWindow", u"Floryn", None))
        self.label_197.setText("")
#if QT_CONFIG(accessibility)
        self.Estes_3.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Estes_3.setText(QCoreApplication.translate("MainWindow", u"Estes", None))
#if QT_CONFIG(accessibility)
        self.Angela_3.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.Angela_3.setText(QCoreApplication.translate("MainWindow", u"Angela", None))
        self.heropic.setText("")
        self.Passive_name_label.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.Passivelabel.setText(QCoreApplication.translate("MainWindow", u"Passive", None))
        self.passivepic.setText("")
        self.passivedesc.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.skill1text.setText(QCoreApplication.translate("MainWindow", u"Skill 1", None))
        self.skill1pic.setText("")
        self.skill1_name.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.skill1desc.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.skill2text.setText(QCoreApplication.translate("MainWindow", u"Skill 2", None))
        self.skill2pic.setText("")
        self.skill2_name.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.skill2desc.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.ultimatetext.setText(QCoreApplication.translate("MainWindow", u"Ultimate", None))
        self.ultipic.setText("")
        self.Ultimatename.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.ultimatedesc.setText(QCoreApplication.translate("MainWindow", u"-", None))
        self.specialskilltext.setText(QCoreApplication.translate("MainWindow", u"Special Skill", None))
        self.specialskilldesc.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.specialskillpic.setText(QCoreApplication.translate("MainWindow", u"None", None))
        self.Specialskillname.setText(QCoreApplication.translate("MainWindow", u"None", None))
    # retranslateUi

